export const columns = [
  {
    label: "Property Image",
    field: "property_image",
  },
  {
    label: "Title",
    field: "title",
  },
  {
    label: "Location",
    field: "location",
  },
  {
    label: "Price",
    field: "price",
  },
  {
    label: "Property Type",
    field: "property_type",
  },
  {
    
    size: 2500,label: "Size",
    field: "size",
  },
  {
    label: "Bedrooms",
    field: "bedrooms",
  },
  {
    label: "Bathrooms",
    field: "barhrooms",
  },
  {
    label: "Status",
    field: "status",
  },
  {
    label: "Assigned Salesperson",
    field: "assigned_salesperson",
  },
  {
    label: "Action",
    field: "action",
  },
];

export const tableData = [
  {
    id: 1,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    assigned_salesperson: "John Doe",
  },
  {
    id: 2,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "under contract",
    assigned_salesperson: "John Doe",
  },
  {
    id: 3,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "withdrawn",
    assigned_salesperson: "John Doe",
  },
  {
    id: 4,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "sold",
    assigned_salesperson: "John Doe",
  },
  {
    id: 5,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "leased",
    assigned_salesperson: "John Doe",
  },
  {
    id: 6,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    assigned_salesperson: "John Doe",
  },
  {
    id: 7,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "coming soon",
    assigned_salesperson: "John Doe",
  },
  {
    id: 8,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    assigned_salesperson: "John Doe",
  },
  {
    id: 9,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "under contract",
    assigned_salesperson: "John Doe",
  },
  {
    id: 10,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "withdrawn",
    assigned_salesperson: "John Doe",
  },
  {
    id: 11,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "sold",
    assigned_salesperson: "John Doe",
  },
  {
    id: 12,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "leased",
    assigned_salesperson: "John Doe",
  },
  {
    id: 13,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    assigned_salesperson: "John Doe",
  },
  {
    id: 14,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "coming soon",
    assigned_salesperson: "John Doe",
  },
  {
    id: 15,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    assigned_salesperson: "John Doe",
  },
  {
    id: 16,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "under contract",
    assigned_salesperson: "John Doe",
  },
  {
    id: 17,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "withdrawn",
    assigned_salesperson: "John Doe",
  },
  {
    id: 18,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "sold",
    assigned_salesperson: "John Doe",
  },
  {
    id: 19,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "leased",
    assigned_salesperson: "John Doe",
  },
  {
    id: 20,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    assigned_salesperson: "John Doe",
  },
  {
    id: 21,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "coming soon",
    assigned_salesperson: "John Doe",
  },
];

export const rows = tableData
