export const columns = [
  // {
  //   label: "Property Image",
  //   field: "property_image",
  // },
  {
    label: "Address",
    field: "Address",
  },
  {
    label: "Property Type",
    field: "property_type",
  },
  {
    
    label: "No of Units",
    field: "size",
  },
  {
    label: "Owner & Address",
    field: "property_type",
  },
  {
    label: "Tel Number",
    field: "Tel Number",
  },
  {
    label: "Status",
    field: "status",
  },
  
  {
    label: "Assigned Broker",
    field: "assigned_broker",
  },
  // {
  //   label: "Title",
  //   field: "title",
  // },
  // {
  //   label: "Location",
  //   field: "location",
  // },
  // {
  //   label: "Price",
  //   field: "price",
  // },
 
  // {
  //   label: "Bedrooms",
  //   field: "bedrooms",
  // },
  // {
  //   label: "Bathrooms",
  //   field: "barhrooms",
  // },

  {
    label: "Action",
    field: "action",
  },
];

export const tableData = [
  {
    id: 1,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    assigned_salesperson: "John Doe",
    owneraddress: "Alice Johnson, 123 Elm Street, Springfield, IL",
    telno: "555-1234",
    address: "123 Elm Street, Springfield, IL"
  },
  {
    id: 2,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "under contract",
    assigned_salesperson: "John Doe",
    owneraddress: "Bob Smith, 456 Oak Street, Springfield, IL",
    telno: "555-2345",
    address: "456 Oak Street, Springfield, IL"
  },
  {
    id: 3,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "withdrawn",
    assigned_salesperson: "John Doe",
    owneraddress: "Charlie Lee, 789 Pine Street, Springfield, IL",
    telno: "555-3456",
    address: "789 Pine Street, Springfield, IL"
  },
  {
    id: 4,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "sold",
    assigned_salesperson: "John Doe",
    owneraddress: "Diana Moore, 101 Maple Avenue, Springfield, IL",
    telno: "555-4567",
    address: "101 Maple Avenue, Springfield, IL"
  },
  {
    id: 5,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "leased",
    assigned_salesperson: "John Doe",
    owneraddress: "Ethan Green, 202 Birch Lane, Springfield, IL",
    telno: "555-5678",
    address: "202 Birch Lane, Springfield, IL"
  },
  {
    id: 6,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    assigned_salesperson: "John Doe",
    owneraddress: "Faith Adams, 303 Cedar Road, Springfield, IL",
    telno: "555-6789",
    address: "303 Cedar Road, Springfield, IL"
  },
  {
    id: 7,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "coming soon",
    assigned_salesperson: "John Doe",
    owneraddress: "George Harris, 404 Walnut Street, Springfield, IL",
    telno: "555-7890",
    address: "404 Walnut Street, Springfield, IL"
  },
  {
    id: 8,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    assigned_salesperson: "John Doe",
    owneraddress: "Hannah Clark, 505 Redwood Drive, Springfield, IL",
    telno: "555-8901",
    address: "505 Redwood Drive, Springfield, IL"
  },
  {
    id: 9,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "under contract",
    assigned_salesperson: "John Doe",
    owneraddress: "Isaac King, 606 Fir Street, Springfield, IL",
    telno: "555-9012",
    address: "606 Fir Street, Springfield, IL"
  },
  {
    id: 10,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "withdrawn",
    assigned_salesperson: "John Doe",
    owneraddress: "Jackie Wright, 707 Cedar Street, Springfield, IL",
    telno: "555-0123",
    address: "707 Cedar Street, Springfield, IL"
  },
  {
    id: 11,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "sold",
    assigned_salesperson: "John Doe",
    owneraddress: "Kevin Walker, 808 Cherry Lane, Springfield, IL",
    telno: "555-1234",
    address: "808 Cherry Lane, Springfield, IL"
  },
  {
    id: 12,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "leased",
    assigned_salesperson: "John Doe",
    owneraddress: "Lily Scott, 909 Maple Road, Springfield, IL",
    telno: "555-2345",
    address: "909 Maple Road, Springfield, IL"
  },
  {
    id: 13,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    assigned_salesperson: "John Doe",
    owneraddress: "Mason Lee, 1010 Oak Lane, Springfield, IL",
    telno: "555-3456",
    address: "1010 Oak Lane, Springfield, IL"
  },
  {
    id: 14,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "coming soon",
    assigned_salesperson: "John Doe",
    owneraddress: "Nora Perez, 1111 Birch Street, Springfield, IL",
    telno: "555-4567",
    address: "1111 Birch Street, Springfield, IL"
  },
  {
    id: 15,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    assigned_salesperson: "John Doe",
    owneraddress: "Oscar Robinson, 1212 Pine Road, Springfield, IL",
    telno: "555-5678",
    address: "1212 Pine Road, Springfield, IL"
  },
  {
    id: 16,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "under contract",
    assigned_salesperson: "John Doe",
    owneraddress: "Paula Harris, 1313 Elm Road, Springfield, IL",
    telno: "555-6789",
    address: "1313 Elm Road, Springfield, IL"
  },
  {
    id: 17,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "withdrawn",
    assigned_salesperson: "John Doe",
    owneraddress: "Quinn Foster, 1414 Cedar Avenue, Springfield, IL",
    telno: "555-7890",
    address: "1414 Cedar Avenue, Springfield, IL"
  },
  {
    id: 18,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "sold",
    assigned_salesperson: "John Doe",
    owneraddress: "Riley Moore, 1515 Maple Avenue, Springfield, IL",
    telno: "555-8901",
    address: "1515 Maple Avenue, Springfield, IL"
  },
  {
    id: 19,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "leased",
    assigned_salesperson: "John Doe",
    owneraddress: "Sophia Taylor, 1616 Redwood Lane, Springfield, IL",
    telno: "555-9012",
    address: "1616 Redwood Lane, Springfield, IL"
  },
  {
    id: 20,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    assigned_salesperson: "John Doe",
    owneraddress: "Thomas Jackson, 1717 Oak Street, Springfield, IL",
    telno: "555-0123",
    address: "1717 Oak Street, Springfield, IL"
  },
  {
    id: 21,
    title: "Modern Family Home",
    location: "Springfield, IL",
    price: "350000",
    property_type: "residential",
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    status: "coming soon",
    assigned_salesperson: "John Doe",
    owneraddress: "Uma Patel, 1818 Fir Avenue, Springfield, IL",
    telno: "555-1234",
    address: "1818 Fir Avenue, Springfield, IL"
  }
];




export const rows = tableData
