import { useEffect, useMemo, useState, useRef } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { toast } from 'react-toastify'
import { useRouter } from 'next/navigation'
import { fetchTemplate } from '../../../store/features/templates/templateSlice'
import { selectTemplates, selectTemplateLoading } from '../../../store/features/templates/templateSelectors'
import { fetchDocumentById, createDocument, updateDocument } from '../../../store/features/documents/documentSlice'
import { selectDocument } from '../../../store/features/documents/documentSelectors'
import { addFullScreenChangeListener, toggleFullScreen } from '../../../libs/utils/fullScreenHelper'

// Generate a random 6-digit unique ID
const generateDocId = () => {
  return Math.floor(100000 + Math.random() * 900000).toString()
}

export default function useDesignDocument(initialDocumentId, templateIdFromQuery) {
  const dispatch = useDispatch()
  const router = useRouter()
  
  // Redux state
  const templates = useSelector(selectTemplates) // Will contain all templates when fetched with all: true
  const document = useSelector(selectDocument)
  const templatesLoading = useSelector(selectTemplateLoading)
  
  // Refs - must be declared before useState that uses them
  const fullScreenRef = useRef(null)
  const docIdGenerated = useRef(false) // Track if doc_id has been generated for this document session

  // Local state
  const [selectedTemplateId, setSelectedTemplateId] = useState('')
  const [clientName, setClientName] = useState('')
  const [loading, setLoading] = useState(false)
  const [editorValue, setEditorValue] = useState('')
  // Only generate doc_id once when component mounts (for new documents)
  // Use a function to ensure it's only called once, not on every render
  const [documentId, setDocumentId] = useState(() => {
    const id = generateDocId()
    docIdGenerated.current = true
    return id
  })
  const [docTitle, setDocTitle] = useState('')
  const [editingId, setEditingId] = useState('')
  const [showEmailModal, setShowEmailModal] = useState(false)
  const [emailLoading, setEmailLoading] = useState(false)
  const [isFullScreen, setIsFullScreen] = useState(false)

  // Reset doc_id generation flag when creating a new document (not editing)
  useEffect(() => {
    if (!initialDocumentId && !editingId) {
      // This is a new document creation, ensure we can generate ID
      if (!docIdGenerated.current) {
        // ID will be generated by useState initializer
        docIdGenerated.current = true
      }
    }
  }, [initialDocumentId, editingId])

  // Fetch ALL templates on mount (using all: true to get unpaginated list)
  useEffect(() => {
    dispatch(fetchTemplate({ all: true }))
  }, [dispatch])

  // Set template from URL query if provided
  useEffect(() => {
    if (templateIdFromQuery && !editingId) {
      setSelectedTemplateId(templateIdFromQuery)
    }
  }, [templateIdFromQuery, editingId])

  // If editing existing document, load it from Redux
  useEffect(() => {
    if (!initialDocumentId) return
    
    setLoading(true)
    dispatch(fetchDocumentById(initialDocumentId))
      .unwrap()
      .then((doc) => {
        if (doc) {
          setEditingId(doc._id)
          setSelectedTemplateId(doc.templateId || '')
          setEditorValue(doc.content || '')
          setClientName(doc.clientName || '')
          // Use existing doc_id from document, don't generate new one
          setDocumentId(doc.doc_id || documentId)
          setDocTitle(doc.title || '')
          docIdGenerated.current = true // Mark as generated to prevent regeneration
        }
      })
      .catch((error) => {
        console.error('Failed to load document for editing', error)
        toast.error('Failed to load document')
      })
      .finally(() => {
        setLoading(false)
      })
  }, [initialDocumentId, dispatch])

  const selectedTemplate = useMemo(() => {
    return templates.find(t => t._id === selectedTemplateId || t.id === selectedTemplateId) || null
  }, [templates, selectedTemplateId])

  useEffect(() => {
    // Only load template content if NOT editing an existing document
    // This prevents overwriting user edits when editing a document
    if (editingId) {
      return; // Skip this effect when editing - preserve existing doc_id
    }
    
    // Only generate doc_id ONCE when creating a new document
    // Don't regenerate when template changes - keep the same ID
    if (!docIdGenerated.current) {
      const newId = generateDocId()
      setDocumentId(newId)
      docIdGenerated.current = true
      console.log(`Generated doc_id once: ${newId}`)
    }
    
    if (selectedTemplate) {
      setEditorValue(selectedTemplate.content || '')
      setDocTitle(selectedTemplate.title || '')
    } else {
      setEditorValue('')
      setDocTitle('')
    }
  }, [selectedTemplateId, editingId, selectedTemplate])

  const regenerateDocumentId = () => {
    const newId = generateDocId()
    setDocumentId(newId)
    docIdGenerated.current = true
    console.log(`Manually regenerated doc_id: ${newId}`)
  }


  const handleSendEmail = () => {
    if (!editorValue.trim()) {
      toast.error('Please add some content to the document first')
      return
    }
    setShowEmailModal(true)
  }

  const handleCloseEmailModal = () => {
    setShowEmailModal(false)
  }

  const handleSendEmailWithPDF = async (emailData) => {
    setEmailLoading(true)
    try {
      // Generate PDF
      const pdfBlob = await generatePDFForEmail()
      
      // Create FormData for email sending
      const formData = new FormData()
      formData.append('email', emailData.email)
      formData.append('subject', emailData.subject)
      formData.append('message', emailData.message)
      formData.append('documentTitle', docTitle || 'Document')
      formData.append('pdf', pdfBlob, `${docTitle || 'Document'}.pdf`)

      // Here you would typically send to your backend API
      // For now, we'll simulate the email sending
      console.log('Email data:', {
        to: emailData.email,
        subject: emailData.subject,
        message: emailData.message,
        attachment: `${docTitle || 'Document'}.pdf`
      })

      // Simulate API call delay
      await new Promise(resolve => setTimeout(resolve, 2000))

      toast.success(`Email sent successfully to ${emailData.email}`)
      setShowEmailModal(false)
    } catch (error) {
      console.error('Error sending email:', error)
      toast.error('Failed to send email. Please try again.')
    } finally {
      setEmailLoading(false)
    }
  }

  const handleSaveDocument = async (retryCount = 0) => {
    if (!editorValue.trim()) {
      toast.error('Nothing to save. Please edit content first.')
      return
    }

    const MAX_RETRIES = 5 // Maximum retry attempts for duplicate ID
    
    try {
      setLoading(true)

      const documentData = {
        templateId: selectedTemplateId || null,
        title: docTitle || (selectedTemplate && selectedTemplate.title) || 'Untitled Document',
        content: editorValue,
        clientName: clientName || '',
        doc_id: documentId || generateDocId(), // Use doc_id for backend
      }

      let result;
      
      if (editingId) {
        // Update existing document
        result = await dispatch(updateDocument({ 
          id: editingId, 
          data: documentData 
        })).unwrap()
        toast.success('Document updated successfully')
      } else {
        // Create new document
        result = await dispatch(createDocument(documentData)).unwrap()
        toast.success('Document created successfully')
      }
      
      router.push('/documents')
      return result._id || result.id
    } catch (error) {
      console.error('Failed to save document', error)
      
      // Check if error is due to duplicate doc_id (only for create, not update)
      const isDuplicateError = 
        !editingId && (
          error?.message?.toLowerCase().includes('duplicate') ||
          error?.message?.toLowerCase().includes('already exists') ||
          error?.message?.toLowerCase().includes('unique') ||
          error?.toLowerCase().includes('duplicate') ||
          error?.toLowerCase().includes('already exists')
        )
      
      if (isDuplicateError && retryCount < MAX_RETRIES) {
        console.log(`Duplicate doc_id detected. Regenerating... (Attempt ${retryCount + 1}/${MAX_RETRIES})`)
        // Generate new ID and retry
        const newDocId = generateDocId()
        setDocumentId(newDocId)
        toast.warning(`Document ID already exists. Trying with new ID: ${newDocId}`)
        
        // Wait a bit before retrying
        await new Promise(resolve => setTimeout(resolve, 300))
        
        // Retry with new ID
        return handleSaveDocument(retryCount + 1)
      } else if (isDuplicateError && retryCount >= MAX_RETRIES) {
        toast.error('Failed to generate unique document ID after multiple attempts. Please try again.')
      } else {
        toast.error(error?.message || `Failed to ${editingId ? 'update' : 'create'} document`)
      }
    } finally {
      if (retryCount === 0) {
        setLoading(false)
      }
    }
  }

  // Full-screen functionality using utility
  const handleFullScreen = () => {
    if (!fullScreenRef.current) return;
    toggleFullScreen(fullScreenRef.current, isFullScreen);
  };

  // Listen for fullscreen change events using utility
  useEffect(() => {
    const cleanup = addFullScreenChangeListener(setIsFullScreen);
    return cleanup;
  }, []);

  return {
    templates,
    selectedTemplateId,
    setSelectedTemplateId,
    clientName,
    setClientName,
    loading,
    handleSendEmail,
    selectedTemplate,
    editorValue,
    setEditorValue,
    documentId,
    regenerateDocumentId,
    docTitle,
    setDocTitle,
    handleSaveDocument,
    isEditing: !!editingId, // Boolean flag for editing mode
    // Email modal props
    showEmailModal,
    emailLoading,
    handleCloseEmailModal,
    handleSendEmailWithPDF,
    // Full-screen props
    isFullScreen,
    fullScreenRef,
    handleFullScreen,
  }
}

