import { useEffect, useMemo, useState, useRef } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { toast } from 'react-toastify'
import { useRouter } from 'next/navigation'
import { fetchTemplate } from '../../../store/features/templates/templateSlice'
import { selectTemplates, selectTemplateLoading } from '../../../store/features/templates/templateSelectors'
import { fetchDocumentById, createDocument, updateDocument, uploadPdfToCloudinary, sendEmailWithDocument } from '../../../store/features/documents/documentSlice'
import { selectDocument } from '../../../store/features/documents/documentSelectors'
import { addFullScreenChangeListener, toggleFullScreen } from '../../../libs/utils/fullScreenHelper'
import { AppRoutes } from '@/constants/appRoutes'

// Generate a random 6-digit unique ID
const generateDocId = () => {
  return Math.floor(100000 + Math.random() * 900000).toString()
}

export default function useDesignDocument(initialDocumentId, templateIdFromQuery) {
  const dispatch = useDispatch()
  const router = useRouter()
  
  // Redux state
  const templates = useSelector(selectTemplates) // Will contain all templates when fetched with all: true
  const document = useSelector(selectDocument)
  const templatesLoading = useSelector(selectTemplateLoading)
  
  // Refs - must be declared before useState that uses them
  const fullScreenRef = useRef(null)
  const docIdGenerated = useRef(false) // Track if doc_id has been generated for this document session

  // Local state
  const [selectedTemplateId, setSelectedTemplateId] = useState('')
  const [clientName, setClientName] = useState('')
  const [loading, setLoading] = useState(false)
  const [editorValue, setEditorValue] = useState('')
  // Only generate doc_id once when component mounts (for new documents)
  // Use a function to ensure it's only called once, not on every render
  const [documentId, setDocumentId] = useState(() => {
    const id = generateDocId()
    docIdGenerated.current = true
    return id
  })
  const [docTitle, setDocTitle] = useState('')
  const [editingId, setEditingId] = useState('')
  const [showEmailModal, setShowEmailModal] = useState(false)
  const [emailLoading, setEmailLoading] = useState(false)
  const [showSaveOnlyModal, setShowSaveOnlyModal] = useState(false)
  const [saveOnlyLoading, setSaveOnlyLoading] = useState(false)
  const [isFullScreen, setIsFullScreen] = useState(false)

  // Reset doc_id generation flag when creating a new document (not editing)
  useEffect(() => {
    if (!initialDocumentId && !editingId) {
      // This is a new document creation, ensure we can generate ID
      if (!docIdGenerated.current) {
        // ID will be generated by useState initializer
        docIdGenerated.current = true
      }
    }
  }, [initialDocumentId, editingId])

  // Fetch ALL templates on mount (using all: true to get unpaginated list)
  useEffect(() => {
    dispatch(fetchTemplate({ all: true }))
  }, [dispatch])

  // Set template from URL query if provided
  useEffect(() => {
    if (templateIdFromQuery && !editingId) {
      setSelectedTemplateId(templateIdFromQuery)
    }
  }, [templateIdFromQuery, editingId])

  // If editing existing document, load it from Redux
  useEffect(() => {
    if (!initialDocumentId) return
    
    setLoading(true)
    dispatch(fetchDocumentById(initialDocumentId))
      .unwrap()
      .then((doc) => {
        if (doc) {
          setEditingId(doc._id)
          setSelectedTemplateId(doc.templateId || '')
          setEditorValue(doc.content || '')
          setClientName(doc.clientName || '')
          // Use existing doc_id from document, don't generate new one
          setDocumentId(doc.doc_id || documentId)
          setDocTitle(doc.title || '')
          docIdGenerated.current = true // Mark as generated to prevent regeneration
        }
      })
      .catch((error) => {
        console.error('Failed to load document for editing', error)
        toast.error('Failed to load document')
      })
      .finally(() => {
        setLoading(false)
      })
  }, [initialDocumentId, dispatch])

  const selectedTemplate = useMemo(() => {
    return templates.find(t => t._id === selectedTemplateId || t.id === selectedTemplateId) || null
  }, [templates, selectedTemplateId])

  useEffect(() => {
    // Only load template content if NOT editing an existing document
    // This prevents overwriting user edits when editing a document
    if (editingId) {
      return; // Skip this effect when editing - preserve existing doc_id
    }
    
    // Only generate doc_id ONCE when creating a new document
    // Don't regenerate when template changes - keep the same ID
    if (!docIdGenerated.current) {
      const newId = generateDocId()
      setDocumentId(newId)
      docIdGenerated.current = true
      console.log(`Generated doc_id once: ${newId}`)
    }
    
    if (selectedTemplate) {
      setEditorValue(selectedTemplate.content || '')
      setDocTitle(selectedTemplate.title || '')
    } else {
      setEditorValue('')
      setDocTitle('')
    }
  }, [selectedTemplateId, editingId, selectedTemplate])

  const regenerateDocumentId = () => {
    const newId = generateDocId()
    setDocumentId(newId)
    docIdGenerated.current = true
    console.log(`Manually regenerated doc_id: ${newId}`)
  }


  const handleSendEmail = () => {
    if (!editorValue.trim()) {
      toast.error('Please add some content to the document first')
      return
    }
    setShowEmailModal(true)
  }

  const handleCloseEmailModal = () => {
    setShowEmailModal(false)
  }

  const handleSendEmailWithPDF = async (emailData, retryCount = 0) => {
    if (!emailData.pdfFile) {
      toast.error('Please select a PDF file')
      return
    }

    if (!editorValue.trim()) {
      toast.error('Nothing to save. Please edit content first.')
      return
    }

    const MAX_RETRIES = 5

    setEmailLoading(true)
    let documentIdForUpload = null
    let cloudinaryUrl = null
    
    try {
      // Step 1: Create document first to get the document ID
      const documentData = {
        templateId: selectedTemplateId || null,
        title: docTitle || (selectedTemplate && selectedTemplate.title) || 'Untitled Document',
        content: editorValue,
        clientName: clientName || '',
        doc_id: documentId || generateDocId(),
      }

      if (editingId) {
        documentIdForUpload = editingId
      } else {
        // Create new document
        try {
          const result = await dispatch(createDocument(documentData)).unwrap()
          documentIdForUpload = result._id || result.id
          toast.success('Document created successfully')
        } catch (createError) {
          // Check if error is due to duplicate doc_id
          const isDuplicateError = 
            createError?.message?.toLowerCase().includes('duplicate') ||
            createError?.message?.toLowerCase().includes('already exists') ||
            createError?.message?.toLowerCase().includes('unique')
          
          if (isDuplicateError && retryCount < MAX_RETRIES) {
            console.log(`Duplicate doc_id detected. Regenerating... (Attempt ${retryCount + 1}/${MAX_RETRIES})`)
            const newDocId = generateDocId()
            setDocumentId(newDocId)
            toast.warning(`Document ID already exists. Trying with new ID: ${newDocId}`)
            
            await new Promise(resolve => setTimeout(resolve, 300))
            
            // Retry with new ID
            return handleSendEmailWithPDF(emailData, retryCount + 1)
          } else if (isDuplicateError && retryCount >= MAX_RETRIES) {
            throw new Error('Failed to generate unique document ID after multiple attempts. Please try again.')
          } else {
            throw createError
          }
        }
      }

      // Close modal and redirect after document creation
      setShowEmailModal(false)
      router.push(AppRoutes.DOCUMENTS)
      setEmailLoading(false)

      // Step 2: Upload PDF to Cloudinary
      // toast.info('Uploading PDF to Cloudinary...')
      const formData = new FormData()
      formData.append('pdf_file', emailData.pdfFile)
      
      try {
        const uploadResult = await dispatch(uploadPdfToCloudinary({ 
          id: documentIdForUpload, 
          file: formData 
        })).unwrap()
        
        // Get Cloudinary public URL from response
        cloudinaryUrl = uploadResult?.pdfUrl || uploadResult?.cloudinaryUrl || uploadResult?.url || uploadResult?.publicUrl || uploadResult?.document?.pdfUrl || uploadResult?.document?.cloudinaryUrl
        
        toast.success('PDF uploaded to Cloudinary')
      } catch (uploadError) {
        // Check for 413 Content Too Large error
        if (uploadError?.response?.status === 413 || uploadError?.status === 413 || uploadError?.message?.includes('413') || uploadError?.message?.toLowerCase().includes('too large')) {
          const fileSizeMB = (emailData.pdfFile.size / 1024 / 1024).toFixed(2)
          throw new Error(`PDF file is too large (${fileSizeMB}MB). Maximum file size is 10MB. Please export a smaller PDF or compress the file.`)
        }
        throw uploadError
      }

      // Step 3: Send email with document
      // toast.info('Sending email...')
      await dispatch(sendEmailWithDocument({ 
        id: documentIdForUpload, 
        email: { email_recipient: emailData.email_recipient } 
      })).unwrap()
      
      toast.success(`Email sent successfully to ${emailData.email_recipient}`)

      // Step 4: Update document with Cloudinary public URL and email address
      const updatedDocumentData = {
        ...documentData,
        email_recipient: emailData.email_recipient,
      }
      
      // Add Cloudinary URL if we have it
      if (cloudinaryUrl) {
        updatedDocumentData.pdfUrl = cloudinaryUrl
        updatedDocumentData.cloudinaryUrl = cloudinaryUrl
      }
      
      await dispatch(updateDocument({ 
        id: documentIdForUpload, 
        data: updatedDocumentData 
      })).unwrap()
      
      // toast.success('Document updated with Cloudinary URL and email')
      
    } catch (error) {
      console.error('Error in save and send flow:', error)
      toast.error(error?.message || 'Failed to save and send document. Please try again.')
      setEmailLoading(false)
    }
  }

  const handleSaveDocument = async () => {
    if (!editorValue.trim()) {
      toast.error('Nothing to save. Please edit content first.')
      return
    }

    // Show email modal instead of directly saving
    // User will upload PDF and enter email, then we'll save, upload, and send
    setShowEmailModal(true)
  }

  const handleSaveOnly = () => {
    if (!editorValue.trim()) {
      toast.error('Nothing to save. Please edit content first.')
      return
    }
    // Show Save Only modal
    setShowSaveOnlyModal(true)
  }

  const handleCloseSaveOnlyModal = () => {
    setShowSaveOnlyModal(false)
  }

  const handleSaveOnlyWithPDF = async (saveData, retryCount = 0) => {
    if (!saveData.pdfFile) {
      toast.error('Please select a PDF file')
      return
    }

    if (!editorValue.trim()) {
      toast.error('Nothing to save. Please edit content first.')
      return
    }

    const MAX_RETRIES = 5

    setSaveOnlyLoading(true)
    let documentIdForUpload = null
    let cloudinaryUrl = null
    
    try {
      // Step 1: Create or update document first to get the document ID
      const documentData = {
        templateId: selectedTemplateId || null,
        title: docTitle || (selectedTemplate && selectedTemplate.title) || 'Untitled Document',
        content: editorValue,
        clientName: clientName || '',
        doc_id: documentId || generateDocId(),
      }

      if (editingId) {
        documentIdForUpload = editingId
        // Update existing document
        await dispatch(updateDocument({ 
          id: editingId, 
          data: documentData 
        })).unwrap()
        console.log('Document updated successfully, ID:', documentIdForUpload)
      } else {
        // Create new document
        try {
          const result = await dispatch(createDocument(documentData)).unwrap()
          documentIdForUpload = result._id || result.id
          console.log('Document created successfully, ID:', documentIdForUpload)
          // Close modal and redirect
      setShowSaveOnlyModal(false)
      setSaveOnlyLoading(false)
      router.push(AppRoutes.DOCUMENTS)
          if (!documentIdForUpload) {
            throw new Error('Failed to get document ID after creation')
          }
        } catch (createError) {
          console.error('Error creating document:', createError)
          // Check if error is due to duplicate doc_id
          const isDuplicateError = 
            createError?.message?.toLowerCase().includes('duplicate') ||
            createError?.message?.toLowerCase().includes('already exists') ||
            createError?.message?.toLowerCase().includes('unique')
          
          if (isDuplicateError && retryCount < MAX_RETRIES) {
            console.log(`Duplicate doc_id detected. Regenerating... (Attempt ${retryCount + 1}/${MAX_RETRIES})`)
            const newDocId = generateDocId()
            setDocumentId(newDocId)
            toast.warning(`Document ID already exists. Trying with new ID: ${newDocId}`)
            
            await new Promise(resolve => setTimeout(resolve, 300))
            
            // Retry with new ID
            return handleSaveOnlyWithPDF(saveData, retryCount + 1)
          } else if (isDuplicateError && retryCount >= MAX_RETRIES) {
            throw new Error('Failed to generate unique document ID after multiple attempts. Please try again.')
          } else {
            throw createError
          }
        }
      }

      if (!documentIdForUpload) {
        throw new Error('Document ID is required for PDF upload')
      }

      // Step 2: Upload PDF to Cloudinary
      console.log('Uploading PDF to Cloudinary for document:', documentIdForUpload)
      
      // Validate file before creating FormData
      if (!saveData.pdfFile || !(saveData.pdfFile instanceof File)) {
        throw new Error('Invalid PDF file. Please select a valid PDF file.')
      }
      
      // Validate file type
      if (saveData.pdfFile.type !== 'application/pdf') {
        throw new Error('Invalid file type. Please select a PDF file.')
      }
      
      // Validate file size (10MB limit)
      const maxSize = 10 * 1024 * 1024 // 10MB
      if (saveData.pdfFile.size > maxSize) {
        const fileSizeMB = (saveData.pdfFile.size / 1024 / 1024).toFixed(2)
        throw new Error(`PDF file is too large (${fileSizeMB}MB). Maximum file size is 10MB.`)
      }
      
      const formData = new FormData()
      formData.append('pdf_file', saveData.pdfFile)
      
      // Verify FormData was created correctly
      if (!formData.has('pdf_file')) {
        throw new Error('Failed to prepare file for upload')
      }
      
      // Log file details for debugging
      console.log('PDF file details:', {
        name: saveData.pdfFile.name,
        size: saveData.pdfFile.size,
        type: saveData.pdfFile.type,
        lastModified: saveData.pdfFile.lastModified
      })
      
      try {
        const uploadResult = await dispatch(uploadPdfToCloudinary({ 
          id: documentIdForUpload, 
          file: formData 
        })).unwrap()
        
        console.log('Upload result:', uploadResult)
        
        // Get Cloudinary public URL from response
        cloudinaryUrl = uploadResult?.pdfUrl || uploadResult?.cloudinaryUrl || uploadResult?.url || uploadResult?.publicUrl || uploadResult?.document?.pdfUrl || uploadResult?.document?.cloudinaryUrl
        
        if (!cloudinaryUrl) {
          console.warn('Cloudinary URL not found in response:', uploadResult)
          // toast.warning('PDF uploaded but URL not found in response')
        } else {
          console.log('PDF uploaded successfully, URL:', cloudinaryUrl)
        }
      } catch (uploadError) {
        console.error('Error uploading PDF:', uploadError)
        console.error('Upload error details:', {
          message: uploadError?.message,
          response: uploadError?.response,
          status: uploadError?.response?.status,
          data: uploadError?.response?.data
        })
        
        // Check for 413 Content Too Large error
        if (uploadError?.response?.status === 413 || uploadError?.status === 413 || uploadError?.message?.includes('413') || uploadError?.message?.toLowerCase().includes('too large')) {
          const fileSizeMB = (saveData.pdfFile.size / 1024 / 1024).toFixed(2)
          throw new Error(`PDF file is too large (${fileSizeMB}MB). Maximum file size is 10MB. Please export a smaller PDF or compress the file.`)
        }
        
        // Check for network errors (axios uses ERR_NETWORK code)
        if (uploadError?.message?.toLowerCase().includes('network') || 
            uploadError?.code === 'NETWORK_ERROR' || 
            uploadError?.code === 'ERR_NETWORK' ||
            uploadError?.name === 'NetworkError' ||
            !uploadError?.response) {
          const networkErrorMsg = 'Network error. Please check your internet connection and try again. If the problem persists, the server may be unavailable.'
          console.error('Network error detected:', networkErrorMsg)
          throw new Error(networkErrorMsg)
        }
        
        // Check for 404 - document not found
        if (uploadError?.response?.status === 404) {
          throw new Error('Document not found. Please try saving the document again.')
        }
        
        // Check for 401/403 - authentication errors
        if (uploadError?.response?.status === 401 || uploadError?.response?.status === 403) {
          throw new Error('Authentication failed. Please log in again.')
        }
        
        // Re-throw with more context
        const errorMsg = uploadError?.response?.data?.message || uploadError?.message || 'Failed to upload PDF'
        throw new Error(errorMsg)
      }

      // Step 3: Update document with Cloudinary public URL
      if (cloudinaryUrl) {
        console.log('Updating document with Cloudinary URL:', cloudinaryUrl)
        const updatedDocumentData = {
          ...documentData,
          pdfUrl: cloudinaryUrl,
          cloudinaryUrl: cloudinaryUrl
        }
        
        await dispatch(updateDocument({ 
          id: documentIdForUpload, 
          data: updatedDocumentData 
        })).unwrap()
        
        console.log('Document updated with PDF URL successfully')
      }
      
      toast.success('Document saved with PDF URL')
      
    } catch (error) {
      console.error('Error in save only flow:', error)
      console.error('Error details:', {
        message: error?.message,
        response: error?.response,
        stack: error?.stack
      })
      
      const errorMessage = error?.response?.data?.message || error?.message || 'Failed to save document. Please try again.'
      toast.error(errorMessage)
      setSaveOnlyLoading(false)
    }
  }

  // Full-screen functionality using utility
  const handleFullScreen = () => {
    if (!fullScreenRef.current) return;
    toggleFullScreen(fullScreenRef.current, isFullScreen);
  };

  // Listen for fullscreen change events using utility
  useEffect(() => {
    const cleanup = addFullScreenChangeListener(setIsFullScreen);
    return cleanup;
  }, []);

  return {
    templates,
    selectedTemplateId,
    setSelectedTemplateId,
    clientName,
    setClientName,
    loading,
    handleSendEmail,
    selectedTemplate,
    editorValue,
    setEditorValue,
    documentId,
    regenerateDocumentId,
    docTitle,
    setDocTitle,
    handleSaveDocument,
    handleSaveOnly,
    isEditing: !!editingId, // Boolean flag for editing mode
    // Email modal props
    showEmailModal,
    emailLoading,
    handleCloseEmailModal,
    handleSendEmailWithPDF,
    // Save Only modal props
    showSaveOnlyModal,
    saveOnlyLoading,
    handleCloseSaveOnlyModal,
    handleSaveOnlyWithPDF,
    // Full-screen props
    isFullScreen,
    fullScreenRef,
    handleFullScreen,
  }
}


