export const columns = [
  {
    label: "Invoice Number",
    field: "invoiceNumber",
  },
  {
    label: "Invoice Date",
    field: "invoiceDate",
  },
  {
    label: "Client's Name",
    field: "client_name",
  },
  {
    label: "Client's Address",
    field: "client_address",
  },
  {
    label: "Responsible Broker",
    field: "responsible_broker",
  },
  {
    label: "Notary Date",
    field: "notary_date",
  },
  {
    label: "Commissions Payable",
    field: "commissions_payable",
  },
  {
    label: "Status",
    field: "status",
  },
  {
    label: "Actions",
    field: "actions",
  },
];


export const tableData = [
  {
    id: 1,
    invoiceNumber: "INV001",
    invoiceDate: "12/10/2024",
    client_name: "John Doe",
    client_address: "123 Main St, Springfield, IL",
    responsible_broker: "Broker A",
    notary_date: "12/11/2024",
    commissions_payable: "2000",
    status: "pending",
    actions: "View/Update",
  },
  {
    id: 2,
    invoiceNumber: "INV002",
    invoiceDate: "11/09/2023",
    client_name: "St. Patric",
    client_address: "456 Oak St, Springfield, IL",
    responsible_broker: "Broker B",
    notary_date: "11/15/2023",
    commissions_payable: "3000",
    status: "sent",
    actions: "View/Update",
  },
  {
    id: 3,
    invoiceNumber: "INV003",
    invoiceDate: "12/04/2024",
    client_name: "Harry",
    client_address: "789 Birch St, Springfield, IL",
    responsible_broker: "Broker C",
    notary_date: "12/05/2024",
    commissions_payable: "5000",
    status: "paid",
    actions: "View/Update",
  },
  {
    id: 4,
    invoiceNumber: "INV004",
    invoiceDate: "08/08/2022",
    client_name: "Aroun",
    client_address: "101 Pine St, Springfield, IL",
    responsible_broker: "Broker D",
    notary_date: "08/09/2022",
    commissions_payable: "7000",
    status: "overdue",
    actions: "View/Update",
  },
  {
    id: 5,
    invoiceNumber: "INV005",
    invoiceDate: "08/08/2022",
    client_name: "Vivek",
    client_address: "202 Cedar St, Springfield, IL",
    responsible_broker: "Broker E",
    notary_date: "08/09/2022",
    commissions_payable: "1500",
    status: "cancelled",
    actions: "View/Update",
  },
  {
    id: 6,
    invoiceNumber: "INV006",
    invoiceDate: "03/02/2025",
    client_name: "Aroun",
    client_address: "303 Maple St, Springfield, IL",
    responsible_broker: "Broker F",
    notary_date: "03/03/2025",
    commissions_payable: "2200",
    status: "refunded",
    actions: "View/Update",
  },
  {
    id: 7,
    invoiceNumber: "INV007",
    invoiceDate: "03/02/2025",
    client_name: "Bla Bla",
    client_address: "404 Elm St, Springfield, IL",
    responsible_broker: "Broker G",
    notary_date: "03/03/2025",
    commissions_payable: "1800",
    status: "partially paid",
    actions: "View/Update",
  },
  {
    id: 8,
    invoiceNumber: "INV008",
    invoiceDate: "12/10/2024",
    client_name: "John Doe",
    client_address: "123 Main St, Springfield, IL",
    responsible_broker: "Broker A",
    notary_date: "12/11/2024",
    commissions_payable: "2000",
    status: "pending",
    actions: "View/Update",
  },
  {
    id: 9,
    invoiceNumber: "INV009",
    invoiceDate: "11/09/2023",
    client_name: "St. Patric",
    client_address: "456 Oak St, Springfield, IL",
    responsible_broker: "Broker B",
    notary_date: "11/15/2023",
    commissions_payable: "3000",
    status: "sent",
    actions: "View/Update",
  },
  {
    id: 10,
    invoiceNumber: "INV010",
    invoiceDate: "12/04/2024",
    client_name: "Harry",
    client_address: "789 Birch St, Springfield, IL",
    responsible_broker: "Broker C",
    notary_date: "12/05/2024",
    commissions_payable: "5000",
    status: "paid",
    actions: "View/Update",
  },
  {
    id: 11,
    invoiceNumber: "INV011",
    invoiceDate: "08/08/2022",
    client_name: "Aroun",
    client_address: "101 Pine St, Springfield, IL",
    responsible_broker: "Broker D",
    notary_date: "08/09/2022",
    commissions_payable: "7000",
    status: "overdue",
    actions: "View/Update",
  },
  {
    id: 12,
    invoiceNumber: "INV012",
    invoiceDate: "08/08/2022",
    client_name: "Vivek",
    client_address: "202 Cedar St, Springfield, IL",
    responsible_broker: "Broker E",
    notary_date: "08/09/2022",
    commissions_payable: "1500",
    status: "cancelled",
    actions: "View/Update",
  },
  {
    id: 13,
    invoiceNumber: "INV013",
    invoiceDate: "03/02/2025",
    client_name: "Aroun",
    client_address: "303 Maple St, Springfield, IL",
    responsible_broker: "Broker F",
    notary_date: "03/03/2025",
    commissions_payable: "2200",
    status: "refunded",
    actions: "View/Update",
  },
  {
    id: 14,
    invoiceNumber: "INV014",
    invoiceDate: "03/02/2025",
    client_name: "Bla Bla",
    client_address: "404 Elm St, Springfield, IL",
    responsible_broker: "Broker G",
    notary_date: "03/03/2025",
    commissions_payable: "1800",
    status: "partially paid",
    actions: "View/Update",
  },
];

export const rows = tableData;
