export const columns = [
  {
    label: "Name",
    field: "Name",
  },
  {
    label: "Phone",
    field: "Phone",
  },
  {
    label: "Email",
    field: "Email",
  },
  {
    label: "Joining Date",
    field: "Joining Date",
  },
  {
    label: "Status",
    field: "Status",
  },
  {
    label: "Action",
    field: "Action",
  },
];

export const tableData = [
  {
    id: 1,
    name: "John Doe",
    phone: "123456789",
    email: "johndoe@gmail.com",
    status: "active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 2,
    name: "Patric",
    phone: "123456789",
    email: "patric@gmail.com",
    status: "in active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 3,
    name: "Janny",
    phone: "123456789",
    email: "Janny@gmail.com",
    status: "in active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 4,
    name: "Aroun",
    phone: "123456789",
    email: "aroun@gmail.com",
    status: "active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 5,
    name: "Vivek",
    phone: "123456789",
    email: "vivek@gmail.com",
    status: "active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 6,
    name: "bla bla",
    phone: "123456789",
    email: "bla@gmail.com",
    status: "in active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 7,
    name: "John Doe",
    phone: "123456789",
    email: "johndoe@gmail.com",
    status: "active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 8,
    name: "Patric",
    phone: "123456789",
    email: "patric@gmail.com",
    status: "in active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 9,
    name: "Janny",
    phone: "123456789",
    email: "Janny@gmail.com",
    status: "in active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 10,
    name: "Aroun",
    phone: "123456789",
    email: "aroun@gmail.com",
    status: "active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 11,
    name: "Vivek",
    phone: "123456789",
    email: "vivek@gmail.com",
    status: "active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 12,
    name: "bla bla",
    phone: "123456789",
    email: "bla@gmail.com",
    status: "in active",
    joining_date: "5 Oct, 2004",
  },

  {
    id: 13,
    name: "John Doe",
    phone: "123456789",
    email: "johndoe@gmail.com",
    status: "active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 14,
    name: "Patric",
    phone: "123456789",
    email: "patric@gmail.com",
    status: "in active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 15,
    name: "Janny",
    phone: "123456789",
    email: "Janny@gmail.com",
    status: "in active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 16,
    name: "Aroun",
    phone: "123456789",
    email: "aroun@gmail.com",
    status: "active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 17,
    name: "Vivek",
    phone: "123456789",
    email: "vivek@gmail.com",
    status: "active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 18,
    name: "bla bla",
    phone: "123456789",
    email: "bla@gmail.com",
    status: "in active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 19,
    name: "John Doe",
    phone: "123456789",
    email: "johndoe@gmail.com",
    status: "active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 20,
    name: "Patric",
    phone: "123456789",
    email: "patric@gmail.com",
    status: "in active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 21,
    name: "Janny",
    phone: "123456789",
    email: "Janny@gmail.com",
    status: "in active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 22,
    name: "Aroun",
    phone: "123456789",
    email: "aroun@gmail.com",
    status: "active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 23,
    name: "Vivek",
    phone: "123456789",
    email: "vivek@gmail.com",
    status: "active",
    joining_date: "5 Oct, 2004",
  },
  {
    id: 24,
    name: "bla bla",
    phone: "123456789",
    email: "bla@gmail.com",
    status: "in active",
    joining_date: "5 Oct, 2004",
  },
];

export const rows = tableData;
